### ISSUE TITLE
Content : First Impressions / First Page

### ISSUE THREAD

**Issue by TheAlty** [RiseVision/rise-web#7]
We need to steer off talking about Rise being a currency as much as possible and concentrate on labelling it as blockchain application platform using words like tokens etc. Currency is not impressive enough for it to be the number one thing we talk about.

**Comment by jdr0dn3y** [comment]
Can you re-write those sections and send them over? I'll get them integrated.

**Comment by TheAlty** [comment]
Old: Rise Crypto Currency and Application Platform

New: Rise User Friendly Decentralized Application and Investment Platform

Old: Welcome to the future of currency, investing, and transactional application development.

New: “Welcome to a future where building and publishing applications just got easier, a place where investing in Real Estate became accessible to anyone no matter where they live… welcome a new chapter in cryptocurrency evolution”

Old: Scalable on Devices.

New: Scalable on Multiple Devices

Old: We are putting massive effort into making our web interface scale across all devices. We want RISE to be accessible to everyone, so we are removing limitations to using RISE wherever we can.
We believe in the original goal of cryptocurrencies, we want a single, universal, easy to use currency, that isn't controlled by a single organization, or even a small group of organizations. We want it accessible, and easy to use for everyone, and ubiquitously usable.

New: We designing everything from the start with no limitations in mind, making our web interface scale across all devices, so no matter where you are access to the RISE platform will be possible with a simple internet connection.
We believe in the original goal of cryptocurrencies, we want a single, universal, easy to use system, that isn't controlled by a single organization, or even a small group of organizations. We want it accessible, and easy to use for everyone, and ubiquitously usable.

**Comment by jdr0dn3y** [comment]
Updated - Let me know if anything else needs to change.

**Comment by TheAlty** [comment]
Welcome to a future where building and publishing applications just got easier... (Page Break)  A place where the potential to invest in Real Estate becomes accessible to anyone no matter where they live (Page Break)… Welcome to RISE, a new chapter in cryptocurrency investments and decentralized applications...

**Comment by TheAlty** [comment]
Redraft of yesterdays first draft....

Replace:We designing everything from the start with no limitations in mind, making our web interface scale across all devices, so no matter where you are access to the RISE platform will be possible with a simple internet connection.
We believe in the original goal of cryptocurrencies, we want a single, universal, easy to use system, that isn't controlled by a single organization, or even a small group of organizations. We want it accessible, and easy to use for everyone, and ubiquitously usable.

Insert: Our number one goal is to make Rise accessible to everybody, this means we're putting massive effort into making our web interface scale across all devices. By keeping within cryptocurrency core values, you'll be able to transfer value, build applications, trade and even invest via an easy to use and decentralized UI.
